### ISSUE TITLE
add autoconf?

### ISSUE THREAD

**Issue by snmsts** [nptcl/npt#1]
I read http://nptcl.hatenablog.com/entry/2019/03/30/124016 and the architecture is good to try on new platform. I would like to try nptcl on HAIKU.
would you like to have autoconf support for npt? It would improve portability.
If so I'll sent pr for that. but It'll non sense if author don't want to support it.

**Comment by nptcl** [comment]
Thany you for reading my blog and send message.
I don't understand HAIKU and autoconf yet, but I'm interested in it.
I will to confirm whether it is possible for npt to implement autoconf.

**Comment by snmsts** [comment]
see the pull request.. I think it need to modify more to much with

**Comment by snmsts** [comment]
Thank you!
